# Port
server:
  port: 8087

# DataSource Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qp_test
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Hibernate Configuration
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

# JaCoCo configuration
jacoco:
  agent:
    include: "*.class"